### ISSUE TITLE
Color of road and player are different

### ISSUE THREAD

**Issue by nevans224** [thyer/CS340winter2016#123]
I started an AI game and clicked red as my color (or green, I'm not sure). Anyways, I get to be the christmas team as my preview to building roads/settlements is Green after I place it my color changes to Red. Also, my color in the bottom left is red but my banner color is green. I'll attach screenshots of what's going on in a comment waaaaay below all of this console mess. Here's all of my console output for reference:
```
java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at client.domestic.DomesticTradeController.update(DomesticTradeController.java:461)
        at java.util.Observable.notifyObservers(Unknown Source)
        at java.util.Observable.notifyObservers(Unknown Source)
        at gameManager.GameManager.setModel(GameManager.java:66)
        at gameManager.GameManager.joinGame(GameManager.java:189)
        at client.join.JoinGameController.createNewGame(JoinGameController.java:148)
        at client.join.NewGameView$1.actionPerformed(NewGameView.java:109)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
server.ServerException: doPost failed: doPost failed: /games/join (http code 400) Bad Request
        at server.ServerProxy.post(ServerProxy.java:122)
        at server.ServerProxy.joinGame(ServerProxy.java:202)
        at gameManager.GameManager.joinGame(GameManager.java:187)
        at client.join.JoinGameController.joinGame(JoinGameController.java:188)
        at client.join.SelectColorView$1.actionPerformed(SelectColorView.java:179)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: server.ServerException: doPost failed: /games/join (http code 400) Bad Request
        at server.ServerProxy.post(ServerProxy.java:96)
        ... 40 more
first stateeeeeeee
inside first called
before model
after model
End of update state = client.states.SetupFirst@9f7cab
 player index: 0
plyer ID: 19
build settlement
building settlement in game manager
ghgfhgfhfghgfhhhhhhrjyxdjrjte5dfhjaxsrtdfsikjfskjrdfxjsdfhcsjdrxfcbhsmjnfbcshbxdajnszdxv
first stateeeeeeee
End of update state = client.states.SetupFirst@9f7cab
first stateeeeeeee
End of update state = client.states.SetupFirst@9f7cab
second state
End of update state = client.states.SetupSecond@1b804ef
 player index: 0
plyer ID: 19
build settlement
building settlement in game manager
ghgfhgfhfghgfhhhhhhrjyxdjrjte5dfhjaxsrtdfsikjfskjrdfxjsdfhcsjdrxfcbhsmjnfbcshbxdajnszdxv
second state
End of update state = client.states.SetupSecond@1b804ef
second state
End of update state = client.states.SetupSecond@1b804ef
not your turn 1
End of update state = client.states.NotYourTurn@13b4cc7
not your turn 1
End of update state = client.states.NotYourTurn@1724f92
normal state
End of update state = client.states.Normal@727d22
```

**Comment by nevans224** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/11450031/13472703/4b421b1c-e073-11e5-9cf2-060cda8f8856.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/11450031/13472701/4b40ef94-e073-11e5-9a2a-98e4dbe90bb8.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/11450031/13472700/4b3f4e78-e073-11e5-9948-374094b12ed9.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/11450031/13472704/4b457f50-e073-11e5-8b02-edfb8b951a25.png)
![screenshot 7](https://cloud.githubusercontent.com/assets/11450031/13472702/4b414516-e073-11e5-9fa0-c0ece02491cb.png)

**Comment by hunterrees** [comment]
@nevans224 I see bad server requests to join a game. Did you try joining games before this one?
