### ISSUE TITLE
Maritime trade doesn't always work

### ISSUE THREAD

**Issue by sadler-j** [thyer/CS340winter2016#179]
I've managed to use it several times, but after a while it won't let me maritime trade. I push the button and nothing happens.

It is the fourth player's turn, with 1 brick and 5 ore. Fourth player can't trade.

![maritimetrade](https://cloud.githubusercontent.com/assets/16617272/13479022/6412c646-e091-11e5-8738-f4006b7bd2ec.PNG)

**Comment by tunadude09** [comment]
It throws the error below if that helps

Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException
        at shared.models.mapClasses.HexMap.getHex(HexMap.java:31)
        at shared.models.mapClasses.Map.isOnPort(Map.java:377)
        at shared.models.mapClasses.Map.getMaritimeTradeRatio(Map.java:672)
        at shared.models.playerClasses.TurnManager.getMaritimeTradeRatio(TurnManager.java:267)
        at shared.models.Game.getMaritimeTradeRatio(Game.java:385)
        at client.maritime.MaritimeTradeController.startTrade(MaritimeTradeController.java:62)
        at client.maritime.MaritimeTradeView$1.actionPerformed(MaritimeTradeView.java:47)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
