### ISSUE TITLE
When the fourth player joins, his game freezes

### ISSUE THREAD

**Issue by yeyyosing** [thyer/CS340winter2016#530]
I've done this twice now.  What i did was create a new game, then have 3 people join the game.  Then I start up a fourth client, click to join the game, click white as my color, and the game then freezes.  It doesn't draw the correct map.  The client said it had a null pointer exception in the TitlePanel with setting the local color.

**Comment by eaglewyng** [comment]
Marking as duplicate because @CaptBoscho logged this previously

**Comment by yeyyosing** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at client.catan.TitlePanel.setLocalPlayerColor(TitlePanel.java:31)
	at client.turntracker.TurnTrackerView.setLocalPlayerColor(TurnTrackerView.java:75)
	at client.turntracker.TurnTrackerController.initializeTurns(TurnTrackerController.java:64)
	at client.turntracker.TurnTrackerController.updateFromModel(TurnTrackerController.java:78)
	at client.turntracker.TurnTrackerController.alert(TurnTrackerController.java:177)

**Comment by thyer** [comment]
Closing as dupe of #515
